import { readdirSync, writeFileSync } from 'node:fs'
import { log } from './_log.mjs'

const SVG_DIR = 'src/features/Emoji/svg'
const OUTPUT = 'src/features/Emoji/emojiMap.ts'

/**
 * EmojiU1F44D.tsx  →  { componentName: 'EmojiU1F44D', codepoint: '1f44d' }
 * EmojiU1F62E200D1F4A8.tsx  →  { componentName: 'EmojiU1F62E200D1F4A8', codepoint: '1f62e200d1f4a8' }
 */
function parseName(file) {
  const base = file.replace(/\.tsx$/, '')
  const m = base.match(/^EmojiU(.+)$/i)
  if (!m) return null
  return {
    componentName: base,
    codepoint: m[1].toLowerCase(),
  }
}

function main() {
  log.step('Generating emojiMap.ts')

  const files = readdirSync(SVG_DIR).filter(
    (f) => f.endsWith('.tsx') && f !== 'index.tsx',
  )

  const entries = files
    .map(parseName)
    .filter(Boolean)
    .sort((a, b) => a.codepoint.localeCompare(b.codepoint))

  const skipped = files.filter((f) => parseName(f) === null)
  for (const f of skipped) {
    log.warn(`${log.file(f)} — doesn't match EmojiU* pattern, skipped`)
  }

  if (entries.length === 0) {
    log.err(`No emoji files found in ${SVG_DIR}`)
    process.exit(1)
  }

  const imports = entries
    .map(
      ({ componentName }) =>
        `import ${componentName} from './svg/${componentName}'`,
    )
    .join('\n')

  const mapEntries = entries
    .map(
      ({ codepoint, componentName }) => `  '${codepoint}': ${componentName},`,
    )
    .join('\n')

  const output = `// AUTO-GENERATED by scripts/generate_emoji_map.mjs
// Don't edit manually. Run \`npm run emoji:build\` to regenerate.

import type { ComponentType, SVGProps } from 'react'

${imports}

export type EmojiComponent = ComponentType<SVGProps<SVGSVGElement>>

export const EMOJI_MAP: Record<string, EmojiComponent> = {
${mapEntries}
}

export const EMOJI_IDS = Object.keys(EMOJI_MAP)
`

  writeFileSync(OUTPUT, output, 'utf-8')
  log.ok(
    `Generated ${log.file(OUTPUT)} with ${log.count(
      entries.length,
      'emoji',
      'emoji',
    )}`,
  )
}

main()
