// AUTO-GENERATED by scripts/generate_emoji_map.mjs
// Don't edit manually. Run `npm run emoji:build` to regenerate.

import type { ComponentType, SVGProps } from 'react'

import EmojiU1F346 from './svg/EmojiU1F346'
import EmojiU1F389 from './svg/EmojiU1F389'
import EmojiU1F440 from './svg/EmojiU1F440'
import EmojiU1F44B from './svg/EmojiU1F44B'
import EmojiU1F44C from './svg/EmojiU1F44C'
import EmojiU1F44D from './svg/EmojiU1F44D'
import EmojiU1F44F from './svg/EmojiU1F44F'
import EmojiU1F47F from './svg/EmojiU1F47F'
import EmojiU1F48B from './svg/EmojiU1F48B'
import EmojiU1F494 from './svg/EmojiU1F494'
import EmojiU1F4A6 from './svg/EmojiU1F4A6'
import EmojiU1F4A9 from './svg/EmojiU1F4A9'
import EmojiU1F4Aa from './svg/EmojiU1F4Aa'
import EmojiU1F4Af from './svg/EmojiU1F4Af'
import EmojiU1F525 from './svg/EmojiU1F525'
import EmojiU1F5Ff from './svg/EmojiU1F5Ff'
import EmojiU1F602 from './svg/EmojiU1F602'
import EmojiU1F605 from './svg/EmojiU1F605'
import EmojiU1F607 from './svg/EmojiU1F607'
import EmojiU1F608 from './svg/EmojiU1F608'
import EmojiU1F609 from './svg/EmojiU1F609'
import EmojiU1F60A from './svg/EmojiU1F60A'
import EmojiU1F60B from './svg/EmojiU1F60B'
import EmojiU1F60C from './svg/EmojiU1F60C'
import EmojiU1F60D from './svg/EmojiU1F60D'
import EmojiU1F60F from './svg/EmojiU1F60F'
import EmojiU1F610 from './svg/EmojiU1F610'
import EmojiU1F612 from './svg/EmojiU1F612'
import EmojiU1F614 from './svg/EmojiU1F614'
import EmojiU1F618 from './svg/EmojiU1F618'
import EmojiU1F61C from './svg/EmojiU1F61C'
import EmojiU1F621 from './svg/EmojiU1F621'
import EmojiU1F622 from './svg/EmojiU1F622'
import EmojiU1F623 from './svg/EmojiU1F623'
import EmojiU1F624 from './svg/EmojiU1F624'
import EmojiU1F628 from './svg/EmojiU1F628'
import EmojiU1F62B from './svg/EmojiU1F62B'
import EmojiU1F62C from './svg/EmojiU1F62C'
import EmojiU1F62D from './svg/EmojiU1F62D'
import EmojiU1F62E from './svg/EmojiU1F62E'
import EmojiU1F62E200D1F4A8 from './svg/EmojiU1F62E200D1F4A8'
import EmojiU1F630 from './svg/EmojiU1F630'
import EmojiU1F631 from './svg/EmojiU1F631'
import EmojiU1F633 from './svg/EmojiU1F633'
import EmojiU1F634 from './svg/EmojiU1F634'
import EmojiU1F635200D1F4Ab from './svg/EmojiU1F635200D1F4Ab'
import EmojiU1F642 from './svg/EmojiU1F642'
import EmojiU1F643 from './svg/EmojiU1F643'
import EmojiU1F644 from './svg/EmojiU1F644'
import EmojiU1F64C from './svg/EmojiU1F64C'
import EmojiU1F64F from './svg/EmojiU1F64F'
import EmojiU1F90C from './svg/EmojiU1F90C'
import EmojiU1F911 from './svg/EmojiU1F911'
import EmojiU1F914 from './svg/EmojiU1F914'
import EmojiU1F917 from './svg/EmojiU1F917'
import EmojiU1F921 from './svg/EmojiU1F921'
import EmojiU1F923 from './svg/EmojiU1F923'
import EmojiU1F924 from './svg/EmojiU1F924'
import EmojiU1F928 from './svg/EmojiU1F928'
import EmojiU1F92A from './svg/EmojiU1F92A'
import EmojiU1F92B from './svg/EmojiU1F92B'
import EmojiU1F92C from './svg/EmojiU1F92C'
import EmojiU1F92D from './svg/EmojiU1F92D'
import EmojiU1F92E from './svg/EmojiU1F92E'
import EmojiU1F92F from './svg/EmojiU1F92F'
import EmojiU1F970 from './svg/EmojiU1F970'
import EmojiU1F972 from './svg/EmojiU1F972'
import EmojiU1F973 from './svg/EmojiU1F973'
import EmojiU1F974 from './svg/EmojiU1F974'
import EmojiU1F979 from './svg/EmojiU1F979'
import EmojiU1F97A from './svg/EmojiU1F97A'
import EmojiU1Fae0 from './svg/EmojiU1Fae0'
import EmojiU1Fae3 from './svg/EmojiU1Fae3'
import EmojiU1Fae4 from './svg/EmojiU1Fae4'
import EmojiU1Fae6 from './svg/EmojiU1Fae6'
import EmojiU1Faea from './svg/EmojiU1Faea'
import EmojiU2753 from './svg/EmojiU2753'
import EmojiU2757 from './svg/EmojiU2757'
import EmojiU2764 from './svg/EmojiU2764'

export type EmojiComponent = ComponentType<SVGProps<SVGSVGElement>>

export const EMOJI_MAP: Record<string, EmojiComponent> = {
  '1f346': EmojiU1F346,
  '1f389': EmojiU1F389,
  '1f440': EmojiU1F440,
  '1f44b': EmojiU1F44B,
  '1f44c': EmojiU1F44C,
  '1f44d': EmojiU1F44D,
  '1f44f': EmojiU1F44F,
  '1f47f': EmojiU1F47F,
  '1f48b': EmojiU1F48B,
  '1f494': EmojiU1F494,
  '1f4a6': EmojiU1F4A6,
  '1f4a9': EmojiU1F4A9,
  '1f4aa': EmojiU1F4Aa,
  '1f4af': EmojiU1F4Af,
  '1f525': EmojiU1F525,
  '1f5ff': EmojiU1F5Ff,
  '1f602': EmojiU1F602,
  '1f605': EmojiU1F605,
  '1f607': EmojiU1F607,
  '1f608': EmojiU1F608,
  '1f609': EmojiU1F609,
  '1f60a': EmojiU1F60A,
  '1f60b': EmojiU1F60B,
  '1f60c': EmojiU1F60C,
  '1f60d': EmojiU1F60D,
  '1f60f': EmojiU1F60F,
  '1f610': EmojiU1F610,
  '1f612': EmojiU1F612,
  '1f614': EmojiU1F614,
  '1f618': EmojiU1F618,
  '1f61c': EmojiU1F61C,
  '1f621': EmojiU1F621,
  '1f622': EmojiU1F622,
  '1f623': EmojiU1F623,
  '1f624': EmojiU1F624,
  '1f628': EmojiU1F628,
  '1f62b': EmojiU1F62B,
  '1f62c': EmojiU1F62C,
  '1f62d': EmojiU1F62D,
  '1f62e': EmojiU1F62E,
  '1f62e200d1f4a8': EmojiU1F62E200D1F4A8,
  '1f630': EmojiU1F630,
  '1f631': EmojiU1F631,
  '1f633': EmojiU1F633,
  '1f634': EmojiU1F634,
  '1f635200d1f4ab': EmojiU1F635200D1F4Ab,
  '1f642': EmojiU1F642,
  '1f643': EmojiU1F643,
  '1f644': EmojiU1F644,
  '1f64c': EmojiU1F64C,
  '1f64f': EmojiU1F64F,
  '1f90c': EmojiU1F90C,
  '1f911': EmojiU1F911,
  '1f914': EmojiU1F914,
  '1f917': EmojiU1F917,
  '1f921': EmojiU1F921,
  '1f923': EmojiU1F923,
  '1f924': EmojiU1F924,
  '1f928': EmojiU1F928,
  '1f92a': EmojiU1F92A,
  '1f92b': EmojiU1F92B,
  '1f92c': EmojiU1F92C,
  '1f92d': EmojiU1F92D,
  '1f92e': EmojiU1F92E,
  '1f92f': EmojiU1F92F,
  '1f970': EmojiU1F970,
  '1f972': EmojiU1F972,
  '1f973': EmojiU1F973,
  '1f974': EmojiU1F974,
  '1f979': EmojiU1F979,
  '1f97a': EmojiU1F97A,
  '1fae0': EmojiU1Fae0,
  '1fae3': EmojiU1Fae3,
  '1fae4': EmojiU1Fae4,
  '1fae6': EmojiU1Fae6,
  '1faea': EmojiU1Faea,
  '2753': EmojiU2753,
  '2757': EmojiU2757,
  '2764': EmojiU2764,
}

export const EMOJI_IDS = Object.keys(EMOJI_MAP)
